services:

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: click
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: 1g
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch-storage:/var/lib/clickhouse
      - ch-logs:/var/log/clickhouse-server/
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
  
  grafana-enterprise:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    cpus: "1.0"
    mem_limit: 1g    
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      
volumes:
  ch-storage: {}
  ch-logs: {}  
  grafana-storage: {}